language: python

python:
  - 3.9

before_install:
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - python -m unittest discover -s Tests

branches:
  only:
    - master
    - development
