language: python

python:
  - 3.9

before_install:
  - pip install -U pip
  - python setup.py install

script:
  - python -m unittest discover -s Tests

branches:
  only:
    - master
    - development
