language: python

python:
  - 3.7

before_install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - python -m unittest discover -s Tests

branches:
  only:
    - master
    - development
